server:
    port: 8080
    servlet:
        context-path: /identity

spring:
    datasource:
        url: "jdbc:postgresql://localhost:5432/IdentityService"
        username: postgres
        password: 0843300042
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    